trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs: 
  - job: mytest
    steps:
    - task: GoTool@0
      inputs:
        version: '1.14'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d -v github.com/Azure/azure-sdk-for-go/...'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      env:
        GO111MODULE: "on"
    - script: |
        go build
      displayName: 'TEST: Run the GO SDK tests'