trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs: 
  - job: mytest
    steps:
    - task: GoTool@0
      inputs:
        version: '1.14'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d -v github.com/Azure/azure-sdk-for-go/services/storagecache/mgmt/2021-03-01/storagecache/'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - script: |
        set -ex
        # NOTE: API version for Go SDK hardcoded to 2020-03-01.
        # TODO: Update when the new Go SDK has been generated.
        pwd
        cd ../../..
        ls
        cd go/src
        ls
        ln -s github.com/Azure/azure-sdk-for-go/services/storagecache/mgmt/2020-03-01/storagecache
        cd storagecache
      displayName: 'SETUP: add and enable useMockCache in SDK'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    - script: |
        go build
      displayName: 'TEST: Run the GO SDK tests'